### ISSUE TITLE
PRLint isn't reporting status, preventing PR from passing all branch checks

### ISSUE THREAD

**Issue by tilleryd** [ewolfe/prlint#114]
Our company is using PRLint in a private repo. Starting yesterday I think, PRLint is failing to return a status check for the PR title. This is preventing me from merging the PR. 

Troubleshooting:

1. Uninstalled/Reinstalled PRLint GitHub app
2. Removed/Added the PRLint status check
3. Changed the PR title

Nothing seems to work. The only alternative at this point is to remove PRLint from the status checks but I don't want to do that.

**Comment by aensidhe** [comment]
@tilleryd it's down: https://stats.uptimerobot.com/ZzYnEf2BW

**Comment by tilleryd** [comment]
@aensidhe I didn't realize there was a status page. Thanks!

**Comment by ewolfe** [comment]
It's back up now, sorry for the interruption!

**Comment by orierel** [comment]
Down again @ewolfe

**Comment by ewolfe** [comment]
So sorry again! It's back up now.
