### ISSUE TITLE
Allow users to set the "Details" URL on validation failure

### ISSUE THREAD

**Issue by cobrabr** [ewolfe/prlint#48]
It would be interesting to be able to set the URL of the "Details" link whenever validation fails. Linking to `prlint.json` (which is what PRLint does now) can be useful, but it there are other useful things that can be linked to that can be equally or even more useful (e.g. an internal PR guidelines article, for example).

**Comment by ewolfe** [comment]
This can definitely be added. I'll accept a PR if you're up for it. Otherwise it might be a few weeks before I get around to it.

**Comment by ewolfe** [comment]
I think a key at the root level would make sense. What are your thoughts?

**Comment by cobrabr** [comment]
That's what I thought as well, a `detailsURL` key at the same level as `message`. I'll try to put a PR in if I can -- I looked at the source, should be straightforward enough to do.
